### ISSUE TITLE
[kube-monitoring] Auto-discovery of Alertmanager configuration

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#443]
## Context

Users who install a `kube-monitoring` plugin in Greenhouse remote cluster and there is already an alerts plugin in the central cluster, the alertmanager configuration should be preconfigured automatically. 

## Tasks

- [ ] feed alertmanger url
- [ ] use the secret to read the certificate Authentication on alert manger input

```yaml
  optionValues:
    - name: alerts.alertmanagers.hosts
      value:
        - alertmanager.domain.dns
        - alertmanagerdomain.dns
    - name: alerts.alertmanagers.tlsConfig.cert
      valueFrom:
        secret:
          key: tls.crt
          name: organisation-prometheus-sso-cert
    - name: alerts.alertmanagers.tlsConfig.key
      valueFrom:
        secret:
          key: tls.key
          name: organisation-prometheus-sso-cert
```
