### ISSUE TITLE
[Perses] Visualize Greenhouse metrics with Perses

### ISSUE THREAD

**Issue by ibakshay** [cloudoperators/greenhouse-extensions#618]
### Priority

(Medium) I'm annoyed but I'll live

### Is your feature request related to a problem?

The Greenhouse metrics should be visualized with the Perses plugin. This will in-turn replace the Plutono plugin to visualize the Greenhouse metrics. Right now, the greenhouse metrics are visualized with the Plutono plugin. 
[link to Plutono dashboard for Greenhouse qa](https://plutono.greenhouse-qa.eu-nl-1.cloud.sap/?orgId=1)
[link to Plutono dashboard for Greenhouse prod](https://plutono.greenhouse.global.cloud.sap/?search=open&folder=current&orgId=1)

### Acceptance Criteria

- [ ] Plutono dashboards needs to be migrated to Perses
- [ ] perses-dashboards need to be added [here](https://github.com/cloudoperators/greenhouse/tree/main/charts/greenhouse)
- [ ] Ingress needs to enabled in the perses plugin.yaml file. Below is the example snippet

```yaml
spec:
  - name: perses.ingress.enabled
     value: true
  - name: perses.ingress.annotations
     value:
        disco: "true"
        kubenertes.io/tls-acme: "true"
  - name: perses.ingress.hosts
     value: 
     - hosts: 
        - perses.greenhouse-qa.eu-nl-1.cloud.sap
  - name: perses.ingress.tls
     value: 
     - hosts: 
        - perses.greenhouse-qa.eu-nl-1.cloud.sap
     secretName: tls-perses-greenhouse-qa-eu-nl-1-cloud-sap
  - name: perses.ingress.ingressClassName:
     value: nginx    
```
