### ISSUE TITLE
[kube-monitoring] Helm template failed with Flux Hub Spoke Controller

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#932]
### Priority

None

### Description

When testing the new Flux Hub Spoke Controller with one of the `kube-monitoring` test cases, the following failed:

```
Helm install failed for release kube-monitoring/kube-monitoring-dev-david with chart kube-monitoring@2.1.2: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
                                     	        	         	     	  line 10: mapping key "plugin" already defined at line 7
```

The issue is, duplicate labels are assigned to resources

- https://github.com/cloudoperators/greenhouse-extensions/blob/d3d0e75d71f60aed6775e413677b695edfd1e507/kube-monitoring/charts/templates/dashboard-configmap.yaml#L9-L11

- https://github.com/cloudoperators/greenhouse-extensions/blob/d3d0e75d71f60aed6775e413677b695edfd1e507/kube-monitoring/charts/templates/_helper.tpl#L116-L132

```yaml
# Source: kube-monitoring/templates/dashboard-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monitoring-dev-david-dashboards-prometheus-json
  labels:
    **plugin**: kube-monitoring-dev-david
    plutono-dashboard: "true"
    plugindefinition: kube-monitoring
    **plugin**: kube-monitoring-dev-david
    app.kubernetes.io/managed-by: Helm
    release: "kube-monitoring-dev-david"
----
# Source: kube-monitoring/charts/kubeMonitoring/charts/prometheus-node-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-monitoring-dev-david-node-exporter
  namespace: kube-monitoring
  labels:
    plugindefinition: kube-monitoring
    plugin: kube-monitoring-dev-david
    helm.sh/chart: prometheus-node-exporter-4.46.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: kube-monitoring-dev-david
    app.kubernetes.io/version: "1.9.1"
    **jobLabel**: node-exporter
    release: kube-monitoring-dev-david
    **jobLabel**: node-exporter
```

### Reproduction steps

1. helm template with the following values:

```yaml
  values:
    absentMetricsOperator.enabled: true
    alerts.alertmanagers.hosts:
    - alertmanager.domain
    - alertmanager.domain
    alerts.enabled: true
    blackboxExporter.enabled: false
    global.commonLabels:
      service: observability
    global.greenhouse.baseDomain: dev.greenhouse.shoot.canary.k8s-hana.ondemand.com
    global.greenhouse.clusterName: dev-david
    global.greenhouse.clusterNames:
    - dev-david
    global.greenhouse.organizationName: ccloud
    global.greenhouse.teamNames: []
    kubeMonitoring.crds.upgradeJob.image.busybox.registry: keppel.global.cloud.sap/ccloud-dockerhub-mirror
    kubeMonitoring.crds.upgradeJob.image.kubectl.registry: keppel.global.cloud.sap/ccloud-registry-k8s-io-mirror
    kubeMonitoring.customRules:
      PrometheusBadConfig:
        severity: warning
      PrometheusErrorSendingAlertsToAnyAlertmanager:
        severity: warning
      PrometheusRemoteStorageFailures:
        severity: warning
      PrometheusRemoteWriteBehind:
        severity: warning
      PrometheusRuleFailures:
        severity: warning
      PrometheusTargetSyncFailure:
        severity: warning
    kubeMonitoring.dashboards.create: true
    kubeMonitoring.defaultRules.additionalRuleLabels:
      service: metrics
      support_group: observability
    kubeMonitoring.defaultRules.create: true
    kubeMonitoring.kube-state-metrics.image.registry: keppel.global.cloud.sap/ccloud-registry-k8s-io-mirror
    kubeMonitoring.kube-state-metrics.prometheus.monitor.http.metricRelabelings:
    - action: replace
      regex: .*
      replacement: dev-david
      sourceLabels:
      - __name__
      targetLabel: cluster
    kubeMonitoring.prometheus-node-exporter.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.prometheus.ingress.enabled: false
    kubeMonitoring.prometheus.persesDatasource: true
    kubeMonitoring.prometheus.prometheusSpec.externalLabels:
      cluster: dev-david
      cluster_type: observability
      organization: ccloud
      region: eu-de-1
    kubeMonitoring.prometheus.prometheusSpec.externalUrl: https://dev-david--4c1c10f.ccloud.greenhouse-qa.eu-nl-1.cloud.sap
    kubeMonitoring.prometheus.prometheusSpec.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.prometheus.prometheusSpec.resources:
      requests:
        memory: 10Gi
    kubeMonitoring.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 100Gi
    kubeMonitoring.prometheus.prometheusSpec.thanos.objectStorageConfig.existingSecret.key: thanos.yaml
    kubeMonitoring.prometheus.prometheusSpec.thanos.objectStorageConfig.existingSecret.name: thanos-dev-david-metrics-objectstore
    kubeMonitoring.prometheus.service.additionalPorts:
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
    kubeMonitoring.prometheusOperator.admissionWebhooks.deployment.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.prometheusOperator.admissionWebhooks.patch.image.registry: keppel.global.cloud.sap/ccloud-registry-k8s-io-mirror
    kubeMonitoring.prometheusOperator.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.prometheusOperator.prometheusConfigReloader.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.prometheusOperator.thanosImage.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    kubeMonitoring.thanosRuler.thanosRulerSpec.image.registry: keppel.global.cloud.sap/ccloud-quay-mirror
    testFramework.image.registry: keppel.global.cloud.sap/ccloud-ghcr-io-mirror
  valuesFrom:
  - kind: Secret
    name: ccloud-prometheus-sso-cert
    targetPath: alerts.alertmanagers.tlsConfig.cert
    valuesKey: tls.crt
  - kind: Secret
    name: ccloud-prometheus-sso-cert
    targetPath: alerts.alertmanagers.tlsConfig.key
    valuesKey: tls.key
```

### Screenshots

```bash

```
